[tox]
requires =
    tox-uv==1.25.0
env_list = pylint, py312, py313, py314
skip_install = true

[testenv:pylint]
runner = uv-venv-lock-runner
package = skip
dependency_groups = dev
commands = pylint scraper

[testenv]
runner = uv-venv-lock-runner
package = skip
dependency_groups = dev
commands = pytest {posargs}
