name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
          cache-suffix: ${{ github.job }}
          cache-python: false

      - name: Install dependencies
        run: uv sync --group dev

      - name: Linter with pylint
        run: uv run pylint scraper

  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    name: unit-tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Chromium
        run: sudo apt-get update && sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache-suffix: ${{ github.job }}-${{ matrix.python-version }}
          cache-python: false

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest

  integration_tests:
    env:
      MEILISEARCH_HOST_URL: "http://127.0.0.1:7700"
      MEILISEARCH_API_KEY: "masterKey"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    name: integration-tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache-suffix: ${{ github.job }}-${{ matrix.python-version }}
          cache-python: false

      - name: Install dependencies for production only
        run: uv sync

      - name: Meilisearch setup with Docker
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest meilisearch --no-analytics --master-key=masterKey

      - name: Run the scraper with basic config
        run: uv run ./docs_scraper $CONFIG_FILE
        env:
          CONFIG_FILE: "tests/config_files_examples/docs-basics.config.json"

      - name: Run the scraper with custom config
        run: uv run ./docs_scraper $CONFIG_FILE
        env:
          CONFIG_FILE: "tests/config_files_examples/docs-custom.config.json"

  image_build:
    name: image-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker image
        run: docker build .
